const specialMappedNames: Record<string, string> = {
  javascript: "JavaScript",
  typescript: "TypeScript",
  golang: "GoLang",
  html: "HTML",
  css: "CSS",
  wasm: "WASM",
  kubeedge: "KubeEdge",
  sql: "SQL",
  cuelang: "CueLang",
  json: "JSON",
  webassembly: "WebAssembly",
  yaml: "YAML",
  dlt: "DLT",
  cli: "CLI",
  cobol: "Cobol",
  graphql: "GraphQL",
  http: "HTTP",
  oci: "OCI",
  api: "API",
  grpc: "GRPC",
  postresql: "PostreSQL",
  ci: "CI",
  ebpf: "EBPF",
  kubearmour: "KubeArmour",
  wordpress: "WordPress",
  cd: "CD",
  cmake: "CMake",
  dns: "DNS",
  elasticsearch: "ElasticSearch",
  gitops: "GitOps",
  hdl: "HDL",
  mongodb: "MongoDB",
  mysql: "MySQL",
  npm: "NPM",
  oop: "OOP",
  openai: "OpenAI",
  openshift: "OpenShift",
  opentelemetry: "OpenTelemetry",
  oras: "ORAS",
  php: "PHP",
  tensorflow: "TensorFlow",
  vscode: "VSCode",
  ai: "AI",
  aws: "AWS",
  cnf: "CNF",
  ffmpeg: "FFMPEG",
  gitlab: "GitLab",
  ibm: "IBM",
  ide: "IDE",
  oops: "OOPS",
  opencv: "OpenCV",
  openebs: "OpenEBS",
  pytorch: "PyTorch",
  reactjs: "ReactJS",
  rocketdb: "RocketDB",
  rocksdb: "RocksDB",
  tcl: "TCL",
  ut: "UT",
  ux: "UX",
  vm: "VM",
  wasmedge: "WasmEdge",
  xml: "XML",
};

export const getFormattedSkillName = (skill: string) => {
  if (skill in specialMappedNames) return specialMappedNames[skill];
  return skill.charAt(0).toUpperCase() + skill.slice(1);
};
